const popularityScores = {
  Football: 100,
  Basketball: 90,
  Tennis: 85,
  'American Football': 80,
  Baseball: 75,
  Volleyball: 70,
  Boxing: 68,
  Hockey: 65,
  Rugby: 60,
  'e-sports': 55,
  Darts: 50,
  Snooker: 48,
  'Ping Pong': 45,
  Futsal: 40,
  Handball: 38,
  Waterpolo: 35,
  'Winter Sports': 30,
  'Beach Soccer': 25,
  Moto: 20,
  Atletica: 15,
  FIFA: 10,
  'Special Games': 5,
  'Special Single': 5,
  Winner: 3,
  Imaginary: 1,
};

export default popularityScores;
